### ISSUE TITLE
Application Development Roadmap

### ISSUE THREAD

**Issue by micahbule** [Jon-Ervin/PUP-Student-Market#1]
## Minimum Viable Product (MVP)
For you final project, I would be requiring you to develop the following features based on the [list](https://github.com/Jon-Ervin/PUP-Student-Market/blob/master/PUP%20Student%20Market%20Features.md) you pushed in this repository:

- [ ] User Registration (including security feature that certifies users to be PUPians)
- [ ] User verification by the Admin
- [ ] Category view of the posted products
- [ ] Ability for users to be sellers and post item offerings
- [ ] Ability for users to be buyers and buy item offerings via Buy Button
- [ ] Ability for buyers and sellers to update transactions (cancel or finish)

## Next Critical Features
The following features are critical for your application such that after the MVP, these would be the next necessary features to be developed:

- [ ] User Profile, including the ability to update profile
- [ ] Product Search, might include advanced search filters
- [ ] User commendations and reports

## Nice-2-Haves (N2Hs)
These features are not that necessary for your application to run smoothly, but they are definitely nice to have if you can throw them in:

- [ ] User ban and reinstate features

## Unmentioned feature?
Any other features in your list not mentioned in this issue are either vague or is left for the developers to decide whether to include it or not.
